import {
  NUMBER_VALUE_NOT_SET,
  STRING_VALUE_NOT_SET,
  DIFFICULTY_VALUE_NOT_SET,
} from "@/constants/Constants";
import type SongRowCache from "./SongRowCache";
import type SongRowSave from "./SongRowSave";

export default interface SongRowCombined
  extends Partial<SongRowCache>, Partial<SongRowSave> {}

export const DEFAULT_SONG_ROW_COMBINED: SongRowCombined = {
  songID: NUMBER_VALUE_NOT_SET,
  gameVersion: NUMBER_VALUE_NOT_SET,
  source: STRING_VALUE_NOT_SET,
  previewStart: STRING_VALUE_NOT_SET,
  previewEnd: STRING_VALUE_NOT_SET,
  shortName: STRING_VALUE_NOT_SET,
  filePath: STRING_VALUE_NOT_SET,
  vocalParts: NUMBER_VALUE_NOT_SET,
  songName: STRING_VALUE_NOT_SET,
  artist: STRING_VALUE_NOT_SET,
  albumName: STRING_VALUE_NOT_SET,
  trackNumber: NUMBER_VALUE_NOT_SET,
  yearRecorded: NUMBER_VALUE_NOT_SET,
  yearReleased: NUMBER_VALUE_NOT_SET,
  genre: STRING_VALUE_NOT_SET,
  guitarDiff: DIFFICULTY_VALUE_NOT_SET,
  drumsDiff: DIFFICULTY_VALUE_NOT_SET,
  bassDiff: DIFFICULTY_VALUE_NOT_SET,
  vocalsDiff: DIFFICULTY_VALUE_NOT_SET,
  bandDiff: DIFFICULTY_VALUE_NOT_SET,
  keysDiff: DIFFICULTY_VALUE_NOT_SET,
  proKeysDiff: DIFFICULTY_VALUE_NOT_SET,
  proGuitarDiff: DIFFICULTY_VALUE_NOT_SET,
  proBassDiff: DIFFICULTY_VALUE_NOT_SET,
  rating: STRING_VALUE_NOT_SET,
  scrollSpeed: NUMBER_VALUE_NOT_SET,
  vocalPercussionBank: STRING_VALUE_NOT_SET,
  drumBank: STRING_VALUE_NOT_SET,
  tonicNote: STRING_VALUE_NOT_SET,
  songTonality: STRING_VALUE_NOT_SET,
  songLength: STRING_VALUE_NOT_SET,
  isMaster: false, // TODO convert to string so can have proper default
  vocalGender: STRING_VALUE_NOT_SET,

  lighterRating: NUMBER_VALUE_NOT_SET,
  playCount: NUMBER_VALUE_NOT_SET,

  drumsTopScore: NUMBER_VALUE_NOT_SET,
  drumsTopScoreDifficulty: NUMBER_VALUE_NOT_SET, // TODO convert difficulties?
  drumsStarsEasy: NUMBER_VALUE_NOT_SET,
  drumsPercentEasy: NUMBER_VALUE_NOT_SET,
  drumsStarsMedium: NUMBER_VALUE_NOT_SET,
  drumsPercentMedium: NUMBER_VALUE_NOT_SET,
  drumsStarsHard: NUMBER_VALUE_NOT_SET,
  drumsPercentHard: NUMBER_VALUE_NOT_SET,
  drumsStarsExpert: NUMBER_VALUE_NOT_SET,
  drumsPercentExpert: NUMBER_VALUE_NOT_SET,

  bassTopScore: NUMBER_VALUE_NOT_SET,
  bassTopScoreDifficulty: NUMBER_VALUE_NOT_SET,
  bassStarsEasy: NUMBER_VALUE_NOT_SET,
  bassPercentEasy: NUMBER_VALUE_NOT_SET,
  bassStarsMedium: NUMBER_VALUE_NOT_SET,
  bassPercentMedium: NUMBER_VALUE_NOT_SET,
  bassStarsHard: NUMBER_VALUE_NOT_SET,
  bassPercentHard: NUMBER_VALUE_NOT_SET,
  bassStarsExpert: NUMBER_VALUE_NOT_SET,
  bassPercentExpert: NUMBER_VALUE_NOT_SET,

  guitarTopScore: NUMBER_VALUE_NOT_SET,
  guitarTopScoreDifficulty: NUMBER_VALUE_NOT_SET,
  guitarStarsEasy: NUMBER_VALUE_NOT_SET,
  guitarPercentEasy: NUMBER_VALUE_NOT_SET,
  guitarStarsMedium: NUMBER_VALUE_NOT_SET,
  guitarPercentMedium: NUMBER_VALUE_NOT_SET,
  guitarStarsHard: NUMBER_VALUE_NOT_SET,
  guitarPercentHard: NUMBER_VALUE_NOT_SET,
  guitarStarsExpert: NUMBER_VALUE_NOT_SET,
  guitarPercentExpert: NUMBER_VALUE_NOT_SET,

  vocalsTopScore: NUMBER_VALUE_NOT_SET,
  vocalsTopScoreDifficulty: NUMBER_VALUE_NOT_SET,
  vocalsStarsEasy: NUMBER_VALUE_NOT_SET,
  vocalsPercentEasy: NUMBER_VALUE_NOT_SET,
  vocalsStarsMedium: NUMBER_VALUE_NOT_SET,
  vocalsPercentMedium: NUMBER_VALUE_NOT_SET,
  vocalsStarsHard: NUMBER_VALUE_NOT_SET,
  vocalsPercentHard: NUMBER_VALUE_NOT_SET,
  vocalsStarsExpert: NUMBER_VALUE_NOT_SET,
  vocalsPercentExpert: NUMBER_VALUE_NOT_SET,

  harmoniesTopScore: NUMBER_VALUE_NOT_SET,
  harmoniesTopScoreDifficulty: NUMBER_VALUE_NOT_SET,
  harmoniesStarsEasy: NUMBER_VALUE_NOT_SET,
  harmoniesPercentEasy: NUMBER_VALUE_NOT_SET,
  harmoniesStarsMedium: NUMBER_VALUE_NOT_SET,
  harmoniesPercentMedium: NUMBER_VALUE_NOT_SET,
  harmoniesStarsHard: NUMBER_VALUE_NOT_SET,
  harmoniesPercentHard: NUMBER_VALUE_NOT_SET,
  harmoniesStarsExpert: NUMBER_VALUE_NOT_SET,
  harmoniesPercentExpert: NUMBER_VALUE_NOT_SET,

  keysTopScore: NUMBER_VALUE_NOT_SET,
  keysTopScoreDifficulty: NUMBER_VALUE_NOT_SET,
  keysStarsEasy: NUMBER_VALUE_NOT_SET,
  keysPercentEasy: NUMBER_VALUE_NOT_SET,
  keysStarsMedium: NUMBER_VALUE_NOT_SET,
  keysPercentMedium: NUMBER_VALUE_NOT_SET,
  keysStarsHard: NUMBER_VALUE_NOT_SET,
  keysPercentHard: NUMBER_VALUE_NOT_SET,
  keysStarsExpert: NUMBER_VALUE_NOT_SET,
  keysPercentExpert: NUMBER_VALUE_NOT_SET,

  proDrumsTopScore: NUMBER_VALUE_NOT_SET,
  proDrumsTopScoreDifficulty: NUMBER_VALUE_NOT_SET,
  proDrumsStarsEasy: NUMBER_VALUE_NOT_SET,
  proDrumsPercentEasy: NUMBER_VALUE_NOT_SET,
  proDrumsStarsMedium: NUMBER_VALUE_NOT_SET,
  proDrumsPercentMedium: NUMBER_VALUE_NOT_SET,
  proDrumsStarsHard: NUMBER_VALUE_NOT_SET,
  proDrumsPercentHard: NUMBER_VALUE_NOT_SET,
  proDrumsStarsExpert: NUMBER_VALUE_NOT_SET,
  proDrumsPercentExpert: NUMBER_VALUE_NOT_SET,

  proGuitarTopScore: NUMBER_VALUE_NOT_SET,
  proGuitarTopScoreDifficulty: NUMBER_VALUE_NOT_SET,
  proGuitarStarsEasy: NUMBER_VALUE_NOT_SET,
  proGuitarPercentEasy: NUMBER_VALUE_NOT_SET,
  proGuitarStarsMedium: NUMBER_VALUE_NOT_SET,
  proGuitarPercentMedium: NUMBER_VALUE_NOT_SET,
  proGuitarStarsHard: NUMBER_VALUE_NOT_SET,
  proGuitarPercentHard: NUMBER_VALUE_NOT_SET,
  proGuitarStarsExpert: NUMBER_VALUE_NOT_SET,
  proGuitarPercentExpert: NUMBER_VALUE_NOT_SET,

  proBassTopScore: NUMBER_VALUE_NOT_SET,
  proBassTopScoreDifficulty: NUMBER_VALUE_NOT_SET,
  proBassStarsEasy: NUMBER_VALUE_NOT_SET,
  proBassPercentEasy: NUMBER_VALUE_NOT_SET,
  proBassStarsMedium: NUMBER_VALUE_NOT_SET,
  proBassPercentMedium: NUMBER_VALUE_NOT_SET,
  proBassStarsHard: NUMBER_VALUE_NOT_SET,
  proBassPercentHard: NUMBER_VALUE_NOT_SET,
  proBassStarsExpert: NUMBER_VALUE_NOT_SET,
  proBassPercentExpert: NUMBER_VALUE_NOT_SET,

  proKeysTopScore: NUMBER_VALUE_NOT_SET,
  proKeysTopScoreDifficulty: NUMBER_VALUE_NOT_SET,
  proKeysStarsEasy: NUMBER_VALUE_NOT_SET,
  proKeysPercentEasy: NUMBER_VALUE_NOT_SET,
  proKeysStarsMedium: NUMBER_VALUE_NOT_SET,
  proKeysPercentMedium: NUMBER_VALUE_NOT_SET,
  proKeysStarsHard: NUMBER_VALUE_NOT_SET,
  proKeysPercentHard: NUMBER_VALUE_NOT_SET,
  proKeysStarsExpert: NUMBER_VALUE_NOT_SET,
  proKeysPercentExpert: NUMBER_VALUE_NOT_SET,

  bandTopScore: NUMBER_VALUE_NOT_SET,
  bandTopScoreDifficulty: NUMBER_VALUE_NOT_SET,
  bandStarsEasy: NUMBER_VALUE_NOT_SET,
  bandPercentEasy: NUMBER_VALUE_NOT_SET,
  bandStarsMedium: NUMBER_VALUE_NOT_SET,
  bandPercentMedium: NUMBER_VALUE_NOT_SET,
  bandStarsHard: NUMBER_VALUE_NOT_SET,
  bandPercentHard: NUMBER_VALUE_NOT_SET,
  bandStarsExpert: NUMBER_VALUE_NOT_SET,
  bandPercentExpert: NUMBER_VALUE_NOT_SET,
};
